\ir get-product.sql
\ir get-product-view.sql
\ir create-product.sql
\ir delete-product.sql
\ir update-product.sql
\ir update-pricing.sql
\ir update-composition.sql
\ir get-markups.sql
\ir get-uoms.sql
\ir search.sql
\ir current-cost.sql
\ir composite-product-gross.sql
