\ir utils.sql
\ir cost.sql
\ir composite-cost.sql
\ir create-cost.sql
\ir create-product.sql
\ir create-uom.sql
\ir delete-product.sql
\ir flatten-product.sql
\ir components.sql
\ir get-uoms.sql
\ir list-products.sql
\ir parts.sql
\ir product.sql
\ir search.sql
\ir flatten-product.sql
\ir create-component.sql
\ir update-component.sql
\ir update-product.sql
