\ir get-product.sql
\ir get-product-view.sql
\ir create-price.sql
\ir create-product.sql
\ir create-product-uom.sql
\ir create-uom.sql
\ir delete-product.sql
\ir update-product.sql
\ir components.sql
\ir get-margins.sql
\ir get-markups.sql
\ir get-price.sql
\ir get-uoms.sql
\ir price.sql
\ir product.sql
\ir search.sql
\ir current-cost.sql
\ir flatten-product.sql
\ir create-component.sql
\ir update-component.sql
\ir update-product-uom.sql
\ir product-gross.sql
\ir get-line-item.sql
