\echo 'Creating SCM functions'
\ir create-item.sql
\ir create-task.sql
\ir create-route.sql
\ir delete-item.sql
\ir delete-route.sql
\ir get-item.sql
\ir get-route.sql
\ir get-task.sql
\ir flatten-item.sql
\ir json-to-boq.sql
\ir json-to-item-boq.sql
\ir insert-item.sql
\ir item-bom.sql
\ir update-item.sql
\ir update-route.sql
\ir item-boq.sql
\ir search-items.sql
\ir search-routes.sql
\ir search-tasks.sql
