\ir create-person.sql
\ir create-organisation.sql
\ir get-address.sql
\ir get-organisation.sql
\ir get-party.sql
\ir get-person.sql
\ir list-party.sql
\ir search-party.sql
\ir core-setting.sql
\ir update-modified.sql
\ir update-organisation.sql
\ir update-person.sql
