\ir create-order.sql
\ir create-quote.sql
\ir get-order.sql
\ir get-quote.sql
\ir get-quotes.sql
\ir get-invoice.sql
\ir get-invoices.sql
\ir get-purchase-order.sql
\ir list-invoices.sql
\ir list-orders.sql
\ir list-quotes.sql
\ir list-purchase-orders.sql
\ir issue-quote.sql
\ir create-line-item.sql
\ir update-invoice.sql
\ir remove-line-item.sql
\ir update-invoice.sql
\ir update-line-item.sql
\ir update-purchase-order.sql
\ir update-quote.sql
