\ir create-line-item.sql
\ir create-invoice.sql
\ir create-order.sql
\ir create-quote.sql
\ir delete-order.sql
\ir invoice-details.sql
\ir line-item.sql
\ir line-items.sql
\ir list-invoices.sql
\ir list-orders.sql
\ir list-quotes.sql
\ir margins.sql
\ir markups.sql
\ir issue-quote.sql
\ir order.sql
\ir price.sql
\ir product-price.sql
\ir quote.sql
\ir remove-line-item.sql
\ir update-invoice.sql
\ir update-line-item.sql
\ir update-order.sql
\ir update-quote.sql
